site_name:        MultivariateSeries
repo_url:         https://gitlab.inria.fr/mourrain/MultivariateSeries
site_description: Polynomial-Exponential series
site_author:      B. Mourrain

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md