name = "PredictMDAPI"
uuid = "df4d2c64-811c-11e9-2782-c5e8d6893c98"
authors = ["Dilum Aluthge <dilum@aluthge.com>", "Brown Center for Biomedical Informatics <bcbi@brown.edu>"]
version = "0.2.0"

[compat]
julia = "^1.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
