name = "PkgUtils"
uuid = "6f897bc9-7a02-494e-b4ae-05ae7ec60539"
authors = ["Arnav Sood"]
version = "0.2.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SnoopCompile = "aa65fe97-06da-5843-b5b1-d5d13cad87d2"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
