name = "MRphy"
uuid = "18c5d748-a4d3-11e9-30ca-051f275622c1"
authors = ["Ray-Lab <tianrluo@users.noreply.github.com>"]
version = "0.1.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulMR = "84966e9a-a839-11e9-29d5-57fe5a7e36c2"

[compat]
julia = "^1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
