name = "TCX"
uuid = "3b8c1752-506b-11e9-3f9b-8db86abc7c68"
authors = ["xue35 "]
version = "0.1.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
