name = "HELICS"
uuid = "81524022-8764-5038-b61c-08cb1f58760f"
authors = ["Dheepak Krishnamurthy <me@kdheepak.com>"]
version = "0.2.2"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
