authors = ["Warren Schweigert"]
name = "StructuralInheritance"
uuid = "eb3e9d2b-04dc-54b3-9584-49775b812a39"
version = "0.2.4"
license = "MIT"



[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "0.7"
