name = "ConceptnetNumberbatch"
uuid = "2d1d9008-b762-11e8-11f1-375fdd6dca71"
authors = ["Corneliu Cofaru <cornel@oxoaresearch.com>"]
version = "0.1.2"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Languages = "8ef0a80b-9436-5d2c-a485-80b904378c43"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
