name = "Theta"
uuid = "42bdb5c4-78fb-11e9-2233-215979c148c4"
authors = ["Chua Lynn <chualynn@berkeley.edu>"]
version = "0.1.0"

[deps]
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

