name = "AdobeGlyphList"
uuid = "715cd884-8f22-55db-b077-449d1f7eef73"
repo = "https://github.com/sambitdash/AdobeGlyphList.jl.git"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
