CI: azure
c_compiler: gcc
c_compiler_version: '7'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
cxx_compiler_version: '7'
docker_image: condaforge/linux-anvil-comp7
extend_keys:
- ignore_build_only_deps
- extend_keys
- ignore_version
- pin_run_as_build
fortran_compiler: gfortran
freetype: 2.9.1
icu: '64.2'
ignore_build_only_deps:
- numpy
- python
libpng: 1.6.35
lua: '5'
numpy: '1.14'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x.x
    max_pin: x.x.x
  freetype:
    max_pin: x
  icu:
    max_pin: x
  libpng:
    max_pin: x.x
  tk:
    max_pin: x.x
python: '3.7'
r_base: '3.5'
target_platform: linux-64
tk: '8.6'
