language: julia

julia:
  - 0.7
  - 1.0

os:
  - linux

notifications:
  email:
    - sunbergzach@gmail.com

# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("BeliefUpdaters"; coverage=true)'

after_success:
  - julia --project -e 'import Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps); include("docs/make.jl")'
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
