name = "PredictMDExtra"
uuid = "d14d998a-9e6b-11e8-16d3-6f2879ea456d"
authors = ["Dilum Aluthge <dilum@aluthge.com>", "Brown Center for Biomedical Informatics <bcbi@brown.edu>"]
version = "0.10.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
GaussianProcesses = "891a1506-143c-57d2-908e-e1f8e92e6de9"
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJModels = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
MemPool = "f9f48841-c794-520a-933b-121f7ba6ed94"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
PGFPlots = "3b7a836e-365b-5785-a47d-02c71176b4aa"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
RemoteFiles = "cbe49d4c-5af1-5b60-bb70-0a60aa018e1b"
Rmath = "79098fc4-a85e-5d69-aa6a-4863f24498fa"
ScikitLearnBase = "6e75b9c4-186b-50bd-896f-2d2496a4843e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Tau = "c544e3c2-d3e5-5802-ac44-44683f340e4a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "^1.1.0"

[extras]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Distributed", "InteractiveUtils", "Test"]
