CONDA_BUILD_SYSROOT: /opt/MacOSX10.10.sdk
c_compiler: gcc
c_compiler_version: '7'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
cxx_compiler_version: '7'
dbus: '1'
docker_image: condaforge/linux-anvil-comp7
expat: '2.2'
extend_keys:
- pin_run_as_build
- ignore_version
- extend_keys
- ignore_build_only_deps
fontconfig: '2.13'
fortran_compiler: gfortran
freetype: 2.9.1
glib: '2.58'
gst_plugins_base: 1.14.4
gstreamer: 1.14.4
icu: '64.2'
ignore_build_only_deps:
- python
- numpy
jpeg: '9'
libpng: 1.6.35
libxml2: '2.9'
lua: '5'
numpy: '1.11'
openssl: 1.1.1a
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  dbus:
    max_pin: x
  expat:
    max_pin: x.x
  fontconfig:
    max_pin: x
  freetype:
    max_pin: x
  icu:
    max_pin: x
  jpeg:
    max_pin: x
  libpng:
    max_pin: x.x
  libxml2:
    max_pin: x.x
  openssl:
    max_pin: x.x.x
  sqlite:
    max_pin: x
  zlib:
    max_pin: x.x
python: '3.7'
r_base: '3.5'
sqlite: '3'
target_platform: linux-64
zlib: '1.2'
