name = "BisectPy"
uuid = "e91bece4-a713-11e8-30d4-f1bdfdaa459e"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
