name = "ErlangTerm"
uuid = "6cf46ab0-e18c-5424-9784-c70c22e5b0c7"
authors = ["Helge Eichhorn <git@helgeeichhorn.de>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
