name = "KernelDensityEstimatePlotting"
uuid = "c43967c8-f634-5d24-8eab-2867546b366b"
keywords = ["KDE", "SLAM", "plotting", "2D", "robotics", "navigation"]
desc = "Visualization tools for the KernelDensityEstimate.jl package."
version = "0.1.1"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
KernelDensityEstimate = "2472808a-b354-52ea-a80e-1658a3c6056d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Cairo = "≥ 0.6"
Colors = "≥ 0.9.4"
Compose = "≥ 0.7.1"
DocStringExtensions = "≥ 0.7"
Fontconfig = "≥ 0.2.0"
Gadfly = "≥ 1.0.0"
KernelDensityEstimate = "≥ 0.5"
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
