name = "Reddit"
uuid = "27c6c700-beb4-11e9-0d5d-570238037c5a"
authors = ["Kenneth Berry <rosskberry@gmail.com>"]
version = "0.1.1"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
ConfParser = "88353bc9-fd38-507d-a820-d3b43837d6b9"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"

[compat]
julia = "1"
