name = "PolynomialTestSystems"
uuid = "4c526841-e1e8-562c-bfa9-9f39d642e243"
authors = ["Sascha Timme <sascha.timme@gmail.com>"]
version = "0.1.4"

[deps]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"
DynamicPolynomials = "^0.1.2, ^0.2, ^0.3"
MultivariatePolynomials = "^0.2.8, ^0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
