name = "PushVectors"
uuid = "36b54c61-190e-5a5f-82d5-6f0a962d7362"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["Test", "BenchmarkTools"]

[compat]
julia = "^1"
