name = "SchwarzChristoffel"
uuid = "6e93f119-a087-51f0-a155-b73ce4943121"
authors = ["Jeff Eldredge <jdeldre@g.ucla.edu>"]
repo = "https://github.com/jdeldre/SchwartzChristoffel.jl.git"
version = "0.1.4"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1"

[extras]
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "NBInclude", "Plots", "Statistics", "PyPlot"]
