name = "JuliaPetra"
uuid = "0a7d185b-be57-59df-ac21-86d8a1799c2e"
authors = ["Neil Lindquist <nslindquist@csbsju.edu>"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
MPI = "0.7.0"
TypeStability = "1.0.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TypeStability = "73ec333a-e3df-5994-9c7a-5ef2077ce03e"

[targets]
test = ["Test", "TypeStability"]
