authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "Entities from Unicode data tables"
keywords = ["Entities", "Unicode"]
license = "MIT"
name = "Unicode_Entities"
uuid = "a8aa15d3-c567-5e9f-b6cc-4b0f97f09cf7"
version = "1.0.1"

[deps]
StrTables = "9700d1a9-a7c8-5760-9816-a99fda30bb8f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1.0.0"
StrTables = "â‰¥ 1.0.0"
