name = "FunctionalTables"
uuid = "19188cdf-3410-574e-a556-e73fa9e4281b"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[targets]
test = ["Statistics", "Test"]
