name = "ModelSanitizer"
uuid = "913cd07a-ab48-11e9-38cf-61416429a70b"
authors = ["Dilum Aluthge <dilum@aluthge.com>"]
version = "0.3.0"

[compat]
BenchmarkTools = "^0.4.2"
Coverage = "^0.9.2"
DataFrames = "=0.18.4"
MLJ = "=0.2.5"
MLJBase = "=0.2.3"
MLJModels = "=0.2.5"
MultivariateStats = "=0.6.0"
PkgBenchmark = "^0.2.2"
StatsBase = "=0.31.0"
StatsModels = "=0.6.2"
TimerOutputs = "^0.5.0"
julia = "^1.1.0"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJModels = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[targets]
test = ["BenchmarkTools", "Coverage", "DataFrames", "MLJ", "MLJBase", "MLJModels", "MultivariateStats", "PkgBenchmark", "Statistics", "StatsBase", "StatsModels", "Test", "TimerOutputs"]
