name = "GmshTools"
uuid = "82e2f556-b1bd-5f1a-9576-f93c0da5f0ee"
authors = ["Pengcheng Shi"]
version = "0.2.2"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
