name = "LocallyWeightedRegression"
uuid = "68d949f0-74a3-5070-a3ac-aa8145b4bcaa"
author = "Júlio Hoffimann <julio.hoffimann@gmail.com>"
version = "0.3.1"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
GeoStatsDevTools = "19e549d1-356f-5655-9f3d-c1d6136da705"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Variography = "04a0146e-e6df-5636-8d7f-62fa9eb0b20c"

[extras]
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
GeoStatsDevTools = "19e549d1-356f-5655-9f3d-c1d6136da705"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VisualRegressionTests = "34922c18-7c2a-561c-bac1-01e79b2c4c92"

[targets]
test = ["GeoStatsBase", "Pkg", "GeoStatsDevTools", "VisualRegressionTests", "Plots", "ImageMagick", "QuartzImageIO", "Random", "Test"]

[compat]
Distances = "≥ 0.7.3"
GeoStatsBase = "≥ 0.4.2"
GeoStatsDevTools = "≥ 0.4.3"
NearestNeighbors = "≥ 0.4.1"
Reexport = "≥ 0.2.0"
StaticArrays = "≥ 0.8.3"
Variography = "≥ 0.3.6"
julia = "1"
