name = "CryptoUtils"
uuid = "04afed74-ac16-11e9-37b6-1352e3e05830"
authors = ["fcasal"]
version = "0.1.0"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
