name = "CorrNoise"
uuid = "0374c0b2-85fe-5995-9aba-c71c9668af00"
authors = ["Maurizio Tomasi <ziotom78@gmail.com>"]
version = "1.0.1"

[compat]
julia = "1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
