name = "MixedSubdivisions"
uuid = "291d046c-3347-11e9-1e74-c3d251d406c6"
authors = ["Sascha Timme <sascha.timme@gmail.com>"]
version = "0.3.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
MultivariatePolynomials = "^0.2.8, ^0.3"
ProgressMeter = "^0.8, ^0.9, ^1.0"
StaticArrays = "^0.9, ^0.10, ^0.11"

[extras]
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
PolynomialTestSystems = "4c526841-e1e8-562c-bfa9-9f39d642e243"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["MultivariatePolynomials", "PolynomialTestSystems", "Test"]
