name = "BitConverter"
uuid = "3a3ce9e8-98e7-11e9-0fa0-055639f146d3"
license = "MIT"
authors = ["Simon Castano <simon@brane.cc>"]
version = "0.1.1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
