name = "PowerDynSolve"
uuid = "b2d36aa5-a2b1-5d23-8bd9-f353e61de00d"
authors = ["Tim Kittel <tim.kittel@elena-international.com>"]
version = "1.0.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PowerDynBase = "7ffb48b1-f436-5a59-a310-b4407da33972"
PowerDynOperationPoint = "95be4243-a2fd-5eef-a7d1-2e97978993e7"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
julia = "1"
DiffEqBase = "5.6.2"
OrdinaryDiffEq = "5"
PowerDynBase = "1"
PowerDynOperationPoint = "1"

[extras]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
PowerDynOperationPoint = "95be4243-a2fd-5eef-a7d1-2e97978993e7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["PowerDynOperationPoint", "Crayons", "Random", "Test"]
