name = "KernelMethods"
uuid = "d79e8f30-5872-11e9-0dab-2d1842b87615"
authors = ["Eric S. Tellez <donsadit@gmail.com>"]
version = "0.1.3"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimilaritySearch = "053f045d-5466-53fd-b400-a066f88fe02a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
SimilaritySearch = "0.3"
julia = "1"
