name = "Exercism"
uuid = "b06d6668-ed87-5b0c-b882-855c8dde7d29"
authors = ["Sascha Mann <git@mail.saschamann.eu>"]
version = "0.1.4"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "^1.0, 0.7"
JSON  = "0.19, 0.20, 0.21"
