name = "SchumakerSpline"
uuid = "65e68595-3a03-5ff5-a6a2-f05fa774f32e"
authors = ["Stuart Baumann <stuart@stuartbaumann.com>"]
version = "1.4.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.0"
