name = "SlurmWorkloadFileGenerator"
uuid = "da235a08-baf4-11e9-2387-6f19a530ddff"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
