name = "BedgraphFiles"
uuid = "85eb9095-274b-55ce-be28-9e90f41ac741"
authors = ["Ciar√°n O'Mara <Ciaran.OMara@utas.edu.au>"]
version = "2.1.2"

[deps]
Bedgraph = "0bcc2ff6-69eb-520d-bede-0374fc5bd2fd"
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
IterableTables = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
TableShowUtils = "5e66a065-1f0a-5976-b372-e0b8c017ca10"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
TableTraitsUtils = "382cd787-c1b6-5bf2-a167-d5b971a19bda"

[compat]
Bedgraph = "^1.1"
FileIO = "^1.0.1"
IterableTables = ">=0.9.0"
IteratorInterfaceExtensions = "^0.1.1, ^1"
TableShowUtils = "^0.2.0"
TableTraits = "^0.4, ^1"
TableTraitsUtils = "^0.3, ^0.4"
julia = "0.7, ^1"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[targets]
test = ["DataFrames", "Test", "Query", "Logging"]
