name = "TrackingHeaps"
version = "0.1.0"
uuid = "d94bfb22-46ad-56c3-87d0-f6c298cb800e"
authors = ["Henrique Becker <henriquebecker91@gmail.com>"]

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1"
