name = "VaxData"
uuid = "a6f58a78-e649-57e2-81bc-1d865c7b74f7"
authors = ["Allen Hill <allenofthehills@gmail.com>"]
version = "0.5.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[targets]
test = ["Test", "InteractiveUtils"]
