desc = "extends accuracy in computation with Float32s"
keywords = ["floating-point", "extended-accuracy", "precision"]
name = "SingleFloats"
uuid = "2b6d1eac-7baa-5078-8adc-e6a3e659f14f"
repo = "https://github.com/JeffreySarnoff/SingleFloats.jl.git"
license = "MIT"
version = "0.1.4"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
