name = "PowerSystemsUnits"
uuid = "c279aad7-7dc9-58d3-995b-109d3f5deb94"
license = "MIT"
author = "Invenia Technical Computing"
version = "0.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Unitful = "0.15"
julia = "~1.0.4, 1.1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
