[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
YaoBlocks = "418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df"
YaoExtensions = "7a06699c-c960-11e9-3c98-9f78548b5f0f"
