name = "LibSymspg"
uuid = "2098c8a6-82c4-11e9-1f54-e72760d085ce"
authors = ["Jason Eu <morty.yu@yahoo.com>"]
version = "0.3.1"

[compat]
julia = "1"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
