authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "Entities from LaTeX data tables"
keywords = ["Entities", "LaTeX"]
license = "MIT"
name = "LaTeX_Entities"
uuid = "9927f19a-46ce-5bdd-a20a-f46a78b61e3d"
version = "1.0.0"

[deps]
StrTables = "9700d1a9-a7c8-5760-9816-a99fda30bb8f"

LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179" # Only needed for build!

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1.0.0"
StrTables = "â‰¥ 1.0.0"
