name = "ChrBase"
uuid = "c13fa7b1-fb91-5a40-8b3c-3aad7fd30002"
keywords = ["Characters"]
license = "MIT"
desc = "Basic functionality for Chr type"
authors = ["ScottPJones <scottjones@alum.mit.edu>"]
version = "1.0.0"

[deps]
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

ModuleInterfaceTools = "5cb8414e-7aab-5a03-a681-351269c074bf"

StrAPI = "69e7dfc3-c4d0-5e14-8d95-d6042a05b383"
CharSetEncodings = "cb9422de-a9d8-5b68-86db-ff05833ab307"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1.0.0"
ModuleInterfaceTools = "≥ 1.0.0"
StrAPI = "≥ 1.0.0"
CharSetEncodings = "≥ 1.0.0"
