name = "SeriesAccelerators"
uuid = "22ff4e98-c178-11e8-26b3-d15618a5f822"
authors = ["James Cook <cookjws@gmail.com>"]
version = "0.1.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
