language: julia

os:
  - linux

julia:
  - 0.6

matrix:
  allow_failures:
    julia: nightly

notifications:
  email: false

branches:
  only:
  - master

#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd())'
#  - julia -e 'Pkg.test("ApproximateBayesianComputing",coverage=true)'
ApproximateBayesianComputing

after_success:
  - julia -e 'ENV["DOCUMENTER_DEBUG"] = "true"; Pkg.add("Documenter"); cd(Pkg.dir("ApproximateBayesianComputing")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("ApproximateBayesianComputing")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
#  - julia -e 'cd(Pkg.dir("ApproximateBayesianComputing")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
