name = "ImageQualityIndexes"
uuid = "2996bd0c-7a13-11e9-2da2-2f5ce47296a9"
authors = ["Johnny Chen <johnnychen94@hotmail.com>"]
version = "0.1.2"

[deps]
ColorVectorSpace = "c3611d14-8923-5661-9e6a-0046d554d3a4"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageDistances = "51556ac3-7006-55f5-8cb3-34580c88182d"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ColorVectorSpace = ">= 0.6"
ImageCore = ">= 0.8.3"
ImageDistances = ">= 0.2.4"
ImageFiltering = ">= 0.6.3"
MappedArrays = ">= 0.2"
OffsetArrays = ">= 0.10"
julia = "1"

[extras]
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
ReferenceTests = "324d217c-45ce-50fc-942e-d289b448e8cf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[targets]
test = ["ImageMagick", "IterTools", "QuartzImageIO", "ReferenceTests", "Test", "TestImages"]
