name = "LorentzVectors"
uuid = "3f54b04b-17fc-5cd4-9758-90c048d965e3"
authors = ["Jean-Loup Tastet <jean-loup.tastet@cern.ch>"]
version = "0.4.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
