name = "SeparatingAxisTheorem2D"
uuid = "33f35c42-577e-5c66-8569-bbf1771cbf32"
authors = ["Ed Schmerling <ednerd@gmail.com>"]
version = "1.0.1"

[deps]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CoordinateTransformations = "≥ 0.5.0"
RecipesBase = "≥ 0.6.0"
StaticArrays = "≥ 0.8.2"
julia = "≥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
