name = "StrFs"
uuid = "299745a8-1dd2-5813-967e-1153b019bdef"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "^0.9, ^0.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
