name = "FastJet"
uuid = "8509a5d2-ae42-11e8-0b46-5d0ace601ee4"
authors = ["Jan Strube <jan.strube@gmail.com>"]
version = "0.1.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
CxxWrap = "0.8.2"
julia = "â‰¥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

