# This file is machine-generated - editing it directly is not advised

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Unitful]]
deps = ["LinearAlgebra", "Random"]
git-tree-sha1 = "75efb362655883381d03004ca53a3a95facb9a54"
uuid = "1986cc42-f94f-5a68-af5c-568840ba703d"
version = "0.16.0"
