name = "KaTeX"
uuid = "07258bb1-70fb-50ed-9200-988f9681c4d2"
authors = ["Pietro Vertechi <pietro.vertechi@neuro.fchampalimaud.org>"]
version = "0.2.0"

[deps]
AssetRegistry = "bf4720bc-e11a-5d0c-854e-bdca1663c893"
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
JSExpr = "97c1335a-c9c5-57fe-bc5d-ec35cebe8660"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"

[compat]
julia = "1"
WebIO = ">=0.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
