name = "MolecularBoxes"
uuid = "aea3f91d-3b18-5712-a377-5bd7ed4ed15b"
authors = ["Tom Lee <contact@tomlee.com.au>"]
version = "1.0.1"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StaticArrays"]
