[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
JuliaDB = "a93385a2-3734-596a-9a66-3cfbb77141e6"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Widgets = "cc8bc4a8-27d6-5769-a93b-9d913e69aa62"
