name = "InterpolatedRejectionSampling"
uuid = "9608d442-472c-11e9-3e14-5b72dbacd115"
desc = "Fast (multivariate) rejection sampling of discrete PDFs using Interpolation.jl"
authors = ["m-wells"]
version = "1.2.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
