name = "LinearAdjoints"
uuid = "3201237a-9847-11e9-0d2a-6d530c977506"
authors = ["Daniel O'Malley <omalled@lanl.gov>"]
version = "0.1.0"

[deps]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaProgTools = "b1909ce5-9a67-5ea4-ba1b-9d85528f5779"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"