name = "Bobby"
uuid = "bd34264e-e812-11e8-1ee8-bfb20fea2fb4"
authors = ["Alessandro Melis <alessandro_melis@rocketmail.com>"]
version = "0.9.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"