name = "Scryfall"
uuid = "26fa0e40-23c6-5e70-8e5d-49a8a0c72583"
authors = ["Moelf <jerryling315@gmail.com>"]
version = "0.1.3"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
julia = "1"
