name = "DualMatrixTools"
uuid = "31f4e45d-be81-5be7-b2dd-bc577b4f7be8"
authors = ["Benoit Pasquier <pasquieb@uci.edu>"]
version = "1.2.5"

[deps]
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "â‰¥ 0.7.0"
