name = "JuliaManager"
uuid = "0cdbb3b1-e653-5045-b8d5-b31a04c2a6c9"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.1"

[deps]
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[compat]
PackageCompiler = "â‰¥ 0.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
