name = "IndexedTables"
uuid = "6deec6e2-d858-57c5-ab9b-e6ca5bd20e43"
version = "0.12.2"

[deps]
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
OnlineStatsBase = "925886fa-5bf2-5e8e-b522-a9147a512338"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
TableTraitsUtils = "382cd787-c1b6-5bf2-a167-d5b971a19bda"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"

[compat]
DataValues = "0.4.6"
IteratorInterfaceExtensions = "0.1.1, 1"
OnlineStatsBase = "0.9.1, 0.10, 0.11, 0.12, 0.13"
PooledArrays = "0.4.1, 0.5"
StructArrays = "0.4"
Tables = "0.2.4"
TableTraits = "0.3, 0.4, 1"
TableTraitsUtils = "0.2.1, 0.3, 0.4, 1"
WeakRefStrings = "0.5.7, 0.6"
julia = "1"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Dates", "Test", "Random", "OnlineStats", "Serialization", "LinearAlgebra"]
