name = "PowerDynOperationPoint"
uuid = "95be4243-a2fd-5eef-a7d1-2e97978993e7"
authors = ["Tim Kittel <tim.kittel@elena-international.com>"]
version = "1.0.0"

[deps]
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
PowerDynBase = "7ffb48b1-f436-5a59-a310-b4407da33972"

[compat]
julia = "^1.0"
PowerDynBase = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
