name = "ProjectiveVectors"
uuid = "01f381cc-face-5a0a-ade9-ef63dc65d628"
authors = ["Sascha Timme <sascha.timme@gmail.com>"]
version = "0.2.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
