[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Autologistic = "05505b62-b0bd-11e8-1cec-1f3e16cbc293"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"