name = "ApproximateComputations"
uuid = "49d1aae2-ae6b-5d26-a063-7cf6630cf99c"
authors = ["Nicholas Timmons <ngtimmons@gmail.com>"]
version = "0.3.3"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ImportAll = "c65182e5-40f4-518f-8165-175b85689199"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
