name = "Reproject"
uuid = "d1dcc2e6-806e-11e9-2897-3f99785db2ae"
authors = ["Mos√® Giordano", "Rohit Kumar"]
version = "0.3.0"

[deps]
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
SkyCoords = "fc659fc5-75a3-5475-a2ea-3da92c065361"
WCS = "15f3aee2-9e10-537f-b834-a6fb8bdb944d"

[compat]
julia = "^1.0.0"

[extras]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Conda", "PyCall", "SHA", "Test"]
