name = "UnivariateFunctions"
uuid = "368b7869-440d-5a68-a3d1-bbc86b0a93b0"
authors = ["Stuart Baumann <stuart@stuartbaumann.com>"]
version = "0.1.2"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SchumakerSpline = "65e68595-3a03-5ff5-a6a2-f05fa774f32e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
