name = "NumberIntervals"
uuid = "978898f6-561e-11e9-3f66-13949d9e5c8a"
authors = ["Josua Grawitter <josua.grawitter@campus.tu-berlin.de>"]
version = "0.1.0"

[deps]
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"

[compat]
julia = "1"
