[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JuliaDB = "a93385a2-3734-596a-9a66-3cfbb77141e6"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
