name = "ValkyrieRobot"
uuid = "c74b26e8-f247-5d24-b013-c11a2bbd97c6"
version = "0.2.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
RigidBodyDynamics = "2"
julia = "1"

[targets]
test = ["Test"]

