name = "ExoplanetsSysSim"
uuid = "e0ba718c-02ec-11e9-384b-dd2930072415"
authors = ["Eric Ford <eford@psu.edu>"]
version = "1.0.1"

[deps]
CORBITS = "19bfd68b-3085-5123-a7aa-2ec83b867ca4"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
CORBITS = ">= 1.0.0"
CSV = ">= 0.4.3"
Combinatorics = ">= 0.7"
Compat = "2.1"
DataFrames = ">= 0.17.1"
Distributions = ">= 0.20"
FileIO = "1"
HypothesisTests = ">= 0.8"
JLD = "0.9"
JLD2 = ">= 0.1.2"
PDMats = ">= 0.9.6"
SpecialFunctions = ">= 0.7.2"
StatsFuns = ">= 0.8.0"
julia = ">= 0.7"
