name = "CompoundPeriods"
uuid = "a216cea6-0a8c-5945-ab87-5ade47210022"
repo = "https://github.com/JeffreySarnoff/CompoundPeriods.jl.git"
author = "Jeffrey Sarnoff"
license = "MIT"
version = "v0.4.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
