name = "jInv"
uuid = "3dacf901-f8cd-5544-86ed-7a705f85c244"
license = "MIT"
desc = "Flexible Framework for Parallel PDE Parameter Estimation"
authors = ["Eran Treister <erantreister@gmail.com>"]
version = "1.0.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
KrylovMethods = "9a2cd570-f05c-5dc1-9209-93ad6f5727f7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ParSpMatVec = "ccf9b6e2-7ea7-596a-9d65-09863b18e8cc"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.0, 0.7, 1.1"
