name = "StressTest"
uuid = "6e3341f8-3a0d-4582-a093-9d6e6d36caf8"
authors = ["Ian <i.r.butterworth@gmail.com>"]
version = "0.1.0"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"

[compat]
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
