name = "Unidecode"
uuid = "967fb449-e509-55aa-8007-234b4096b967"
version = "1.0.2"

[deps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
julia = "â‰¥ 1.0.0"
