name = "RoMEPlotting"
uuid = "238d586b-a4bf-555c-9891-eda6fc5e55a2"
keywords = ["mm-iSAM", "SLAM", "plotting", "2D", "robotics", "navigation"]
desc = "Visualization tools for the RoME.jl package."
version = "0.1.5"

[deps]
ApproxManifoldProducts = "9bbbb610-88a1-53cd-9763-118ce10c1f89"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DistributedFactorGraphs = "b5cc3c7e-6572-11e9-2517-99fb8daf2f04"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IncrementalInference = "904591bb-b899-562f-9e6f-b8df64c7d480"
KernelDensityEstimate = "2472808a-b354-52ea-a80e-1658a3c6056d"
KernelDensityEstimatePlotting = "c43967c8-f634-5d24-8eab-2867546b366b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RoME = "91fb55c2-4c03-5a59-ba21-f4ea956187b8"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ApproxManifoldProducts = "≥ 0.0.3"
Colors = "≥ 0.9.4"
Compose = "≥ 0.7.1"
DocStringExtensions = "≥ 0.7"
Gadfly = "≥ 1.0.0"
Graphs = "≥ 0.10.2"
IncrementalInference = "0.5, 0.6, 0.7, 0.8"
KernelDensityEstimate = "≥ 0.5"
KernelDensityEstimatePlotting = "≥ 0.1"
Reexport = "≥ 0.2"
RoME = "0.3, 0.4, 0.5"
StatsBase = "≥ 0.25"
julia = "1"

[extras]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Cairo", "Fontconfig"]
