name = "DirectGaussianSimulation"
uuid = "b9828eed-09bc-50cb-b95c-f80757bd8d62"
author = "Júlio Hoffimann <julio.hoffimann@gmail.com>"
version = "0.2.1"

[deps]
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Variography = "04a0146e-e6df-5636-8d7f-62fa9eb0b20c"

[extras]
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
GeoStatsDevTools = "19e549d1-356f-5655-9f3d-c1d6136da705"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Variography = "04a0146e-e6df-5636-8d7f-62fa9eb0b20c"
VisualRegressionTests = "34922c18-7c2a-561c-bac1-01e79b2c4c92"

[targets]
test = ["GeoStatsBase", "Pkg", "GeoStatsDevTools", "VisualRegressionTests", "Plots", "ImageMagick", "QuartzImageIO", "Random", "Variography", "Test"]

[compat]
GeoStatsBase = "≥ 0.4.2"
Variography = "≥ 0.3.6"
julia = "1"
