name = "TypedCodeUtils"
uuid = "687fb87b-adea-59d5-9be9-82253b54685d"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
