name = "PhysicalCommunications"
uuid = "afadef72-ae1a-11e9-3795-e55b3621c13e"
version = "0.1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
