name = "MolecularTopologies"
uuid = "57484d9e-382c-5364-a237-1ed6cd00a13f"
authors = ["Tom Lee <contact@tomlee.com.au>"]
version = "1.1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
