name = "CodecXz"
uuid = "ba30903b-d9e8-5048-a5ec-d1f5b0d4b47b"
license = "MIT"
authors = ["Kenta Sato <bicycle1885@gmail.com>"]
version = "0.6.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
BinaryProvider = "0.5"
TranscodingStreams = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
